global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'administration'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44373']
  - job_name: 'authserver'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44340']
  - job_name: 'identity'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44367']
  - job_name: 'gdpr'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44393' ]
  - job_name: 'filemanagement'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44301' ]
  - job_name: 'saas'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44335' ]
  - job_name: 'chat'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44354' ]
  - job_name: 'auditlogging'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44389' ]
  - job_name: 'web'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44334']